llm:
  base_url: "http://192.168.10.41:11434"
  model: "cnjack/mistral-samll-3.1:24b-it-q4_K_S"
  log_path: "prompts.jsonl"

database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "Hello@123952"
  name: "hrms"